"""Add has_injury and injury_location to event_training_entries

Revision ID: 57c9f7fcec55
Revises: 63d8a684d69e
Create Date: 2025-04-05 23:28:21.569245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c9f7fcec55'
down_revision: Union[str, None] = '63d8a684d69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_training_entries', sa.Column('has_injury', sa.Boolean(), nullable=True))
    op.add_column('event_training_entries', sa.Column('injury_location', sa.Enum('leg', 'arm', 'torso', 'head', 'other', name='injurylocationtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_training_entries', 'injury_location')
    op.drop_column('event_training_entries', 'has_injury')
    # ### end Alembic commands ###
