"""Make wellbeing_score nullable in training entries

Revision ID: 94c15a07da82
Revises: 57c9f7fcec55
Create Date: 2025-04-05 23:48:26.412594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c15a07da82'
down_revision: Union[str, None] = '57c9f7fcec55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_training_entries', 'wellbeing_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('personal_training_entries', 'wellbeing_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_training_entries', 'wellbeing_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('event_training_entries', 'wellbeing_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
